### PR TITLE
Update the exif-entry.c

### PR DESCRIPTION
**Pull request by orangesnn**
dividing by zero

### CODE REVIEW

**Comment by msmeissn** [comment]
second hunk:
I wonder if pow(2,x) can ever be zero.
or if in double operations 1. / pow(2,x) can ever be zero.

the first hunk is fine.

**Comment by msmeissn** [comment]
have you seen crashes caused by the second hunk?

**Comment by orangesnn** [comment]
> have you seen crashes caused by the second hunk?

yes。I printed the information of the middle value, the current numerator is a large negative number, which caused zero after pow(2,x)。

I think the numerator here can be negative, but the value is too large to exceed the current processing method, so it is better to increase the limit on pow(2,x)。How do you think about this？

**Comment by msmeissn** [comment]
thanks!

**Pull request merged**
