### PR TITLE
Offset time tags added

### PR DESCRIPTION
**Pull request by cescobaz**
Hello! (this is my first github PR 😄 )

I added the following tags (in the correct order for tags table/enum):

- 0x9010 OffsetTime
- 0x9011 OffsetTimeOriginal
- 0x9012 OffsetTimeDigitized

Hope you merge it.

Thanks for the great library!

### CODE REVIEW

**Comment by msmeissn** [comment]
thx!

**Comment by lovell** [comment]
Hello, the libexif master branch currently fails to build and it looks like it might be due to the inclusion of the `±` character in this change.

https://github.com/libexif/libexif/blob/da9b2a8d1c222660f5e98057327d5ee97613e84f/libexif/exif-tag.c#L550

```
make  all-recursive
make[1]: Entering directory '/src/libexif'
Making all in m4m
make[2]: Entering directory '/src/libexif/m4m'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/src/libexif/m4m'
Making all in po
make[2]: Entering directory '/src/libexif/po'
make libexif-12.pot-update
make[3]: Entering directory '/src/libexif/po'
sed -e '/^#/d' remove-potcdate.sin > t-remove-potcdate.sed
mv t-remove-potcdate.sed remove-potcdate.sed
/usr/bin/xgettext --default-domain=libexif-12 --directory=.. \
  --add-comments=TRANSLATORS: --keyword=_ --keyword=N_ \
  --files-from=./POTFILES.in \
  --copyright-holder='Lutz Mueller and others' \
  --msgid-bugs-address='libexif-devel@lists.sourceforge.net'
/usr/bin/xgettext: Non-ASCII string at libexif/exif-tag.c:550.
                   Please specify the source encoding through --from-code.
Makefile:161: recipe for target 'libexif-12.pot-update' failed
make[3]: *** [libexif-12.pot-update] Error 1
make[3]: Leaving directory '/src/libexif/po'
Makefile:185: recipe for target 'libexif-12.pot' failed
make[2]: *** [libexif-12.pot] Error 2
make[2]: Leaving directory '/src/libexif/po'
Makefile:521: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/src/libexif'
Makefile:405: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by cescobaz** [comment]
I opened #62 but some checks fail anyway

**Comment by msmeissn** [comment]
can you try agan now?

**Pull request merged**
