### PR TITLE
Update libexif.pc, Doxyfiles and pkg-config detection

### PR DESCRIPTION
**Pull request by hughmcmaster**
This patchset:

- Updates Doxyfile.in and Doxyfile-internals.in to remove several compile-time warnings about obsolete configuration variables.
- Updates libexif to use PKG_PROG_PKG_CONFIG to better support cross-compilation.

### CODE REVIEW

**Comment by dfandrich** [comment]
On Tue, Mar 05, 2019 at 11:06:58AM +0000, Hugh McMaster wrote:
>   • Fixes the Cflags directory location in libexif.pc. Header files are
>     currently installed in /libexif, but the libexif.pc file does not reflect
>     this.

Programs are expected to include libexif header files with include statements
like #include <libexif/exif-loader.h>  Does this not work?

>   • Updates Doxyfile.in and Doxyfile-internals.in to remove several
>     compile-time warnings about obsolete configuration variables.

Were these files entirely upgraded automatically or are there manual changes in
there as well?

**Comment by hughmcmaster** [comment]
> Programs are expected to include libexif header files with include statements like #include <libexif/exif-loader.h> Does this not work?

Yes, it does work. For some reason, Debian ships this patch. Of course, Debian looks in `includedir` by default, so `${includedir}/libexif` is (probably) never used. I'll drop this patch from the PR and the Debian package.

>>• Updates Doxyfile.in and Doxyfile-internals.in to remove several compile-time warnings about obsolete configuration variables.
> Were these files entirely upgraded automatically or are there manual changes in there as well?

These were automatically upgraded via `doxygen -u <filename>`.

**Comment by hughmcmaster** [comment]
Hi Dan, did I answer all of your questions re this patchset?

**Comment by dfandrich** [comment]
The HTML_FOOTER lines need fixing up.

**Comment by hughmcmaster** [comment]
Re-opening this PR. HTML_FOOTER configuration is now fixed.

**Pull request closed without merging**
