### PR TITLE
Update Doxyfile templates and remove several unused m4 files

### PR DESCRIPTION
**Pull request by hughmcmaster**
This patchset:

- Updates Doxyfile.in and Doxyfile-internals.in to remove several compile-time warnings about obsolete configuration variables.
- Removes several unused m4 files.

### CODE REVIEW

**Comment by dfandrich** [comment]
It suddenly occurred to me that libexif doesn't actually depend on any special
libraries (except for testing) and that it doesn't use pkg-config to find
anything. I suspect gp-check-library.m4 can just be deleted wholesale. The
whole m4m directory was copied into git from a separate repo that was shared by
a number of projects, so there are likely other unused files in there that
could be removed.

**Comment by hughmcmaster** [comment]
Okay. I’ll take a look and see what macro files are unused.

Thanks

**Comment by hughmcmaster** [comment]
Hi @dfandrich,

I've updated this PR as per our discussion. This version removes several unused m4 files from the `m4m` directory.

Out of interest, how do you run the tests? I'm using Debian and `failmalloc` hasn't been packaged for years.

Let me know if you need any further changes.

**Comment by dfandrich** [comment]
Looks good! But please squash the changes into two commits, one for Doxygen and one for the m4 files.

I built libfailmalloc from sources manually and keep a copy of the binary around to point configure at. I looked around for a supported library that does something similar but didn't find one. If you're aware of one, I'm happy to switch to that.

**Comment by hughmcmaster** [comment]
@dfandrich I've squashed the commits into two patches, as you requested.

Thanks for your patience on this work.

**Comment by dfandrich** [comment]
Thanks for the patch!

**Pull request merged**
