### PR TITLE
Make exif_entry_initialize() set up entries in the GPS ifd

### PR DESCRIPTION
**Pull request by hlewin**
We need format and component infos in the ExifEntry to decide how to parse string-representations. Sadly exif_entry_initialize() does not set up this info for the GPS ifd.

### CODE REVIEW

**Comment by msmeissn** [comment]
While I merged this now, was rthere a specific reason you closed this before?

**Comment by hlewin** [comment]
@msmeissn Unforunately, yes - the initial commits contained some bugs, so needed further work.
Then I wanted to add tests for complete coverage, but haven't found time to do so, yet.
I was unsure if that feature is actually wanted so this wasn't high on my priority list.

**Comment by msmeissn** [comment]
hmm, i reverted it again from master branch then if there are bugs ... sorry :/

It seems there is interest in it though.

**Comment by hlewin** [comment]
If there is interest, I can supply the missing test.
The bug itself, as said, should be fixed - we are using the patch in production for some time now.
Should I open another MR then when I am done?

**Comment by msmeissn** [comment]
I think there is interest, so I would welcome it :)

**Pull request merged**
