### PR TITLE
Windows: use localtime_s() if available

### PR DESCRIPTION
**Pull request by vtorri**

### CODE REVIEW

**Comment by msmeissn** [comment]
i think we could avoid the host checking and just check for the function instead and use it if we find it... this simplifies this construct?

**Comment by vtorri** [comment]
but i have found this : https://docs.oracle.com/cd/E88353_01/html/E37843/localtime-s-3c.html
i seems that on solaris, localtime_s is available, with the same signatture than localtime_r

**Comment by vtorri** [comment]
or i can just write in the code something like that
```
#ifdef _WIN32
  // usage of localtime_s
#elif HAVE_LOCALTIME_R
  // usage of localtime_r
#else
  //usage of localtime 
```

with no check in configure.ac

**Comment by vtorri** [comment]
and even, on Windows, usage of _localtime64_s (see https://docs.microsoft.com/fr-fr/cpp/c-runtime-library/reference/localtime-s-localtime32-s-localtime64-s?view=msvc-160)

**Comment by vtorri** [comment]
so ?

**Pull request closed without merging**
